language: java

jdk:
  - openjdk8
  - openjdk11

os:
  - linux
  - osx
  # - windows

osx_image:
  - xcode9.1  # used for JDK 8
  - xcode9.3  # used for OpenJDK 11

matrix:
  exclude:
    # these are not valid for Linux
    - os: linux
      osx_image: xcode9.1
    - os: linux
      osx_image: xcode9.3

    # these are not valid for Windows
    - os: windows
      osx_image: xcode9.1
    - os: windows
      osx_image: xcode9.3

    # these are instead included via `osx_image` on OSX
    - os: osx
      jdk: openjdk8
    - os: osx
      jdk: openjdk11

#addons:
#  apt:
#    packages:
#      - graphviz

# make sure the correct java is available
install:
  - |
    if [ "${TRAVIS_OS_NAME}" == osx ]; then
      if xcodebuild -version | grep 9.1; then
        # xcode 9.1
        export JAVA_HOME=$(/usr/libexec/java_home)
      else
        # xcode 9.3
        brew tap AdoptOpenJDK/openjdk || exit $?
        brew cask install adoptopenjdk11 || exit $?
      fi
    fi
    echo "JAVA_HOME=${JAVA_HOME}"
    which java && java -version

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2

branches:
    except:
        - gh-pages

notifications:
    email:
        - lennart.jorelid@gmail.com
