language: java

jdk:
  - openjdk8
  - openjdk11

os:
  - linux
  - osx
  - windows

osx_image: xcode9.3

addons:
  apt:
    packages:
      - graphviz

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2

branches:
    except:
        - gh-pages

notifications:
    email:
        - lennart.jorelid@gmail.com
