language: shell

os:
  - linux
  - osx
  - windows

env:
  - JAVA_VERSION=8
  - JAVA_VERSION=11

dist:
  xenial

osx_image:
  - xcode9.1  # used for JDK 8

# make sure the correct java is available
install:
  - |
    if [ "${TRAVIS_OS_NAME}" == linux ]; then
      if ["${JAVA_VERSION}" == "8"]; then
        jdk_switcher use openjdk8
      else
        jdk_switcher use openjdk11
      endif
    elif [ "${TRAVIS_OS_NAME}" == osx ]; then
      if ["${JAVA_VERSION}" == "8"]; then
      else
        brew tap AdoptOpenJDK/openjdk || exit $?
        brew cask install adoptopenjdk11 || exit $?
      fi
      export JAVA_HOME=$(/usr/libexec/java_home)
    elif [ "${TRAVIS_OS_NAME}" == windows ]; then
      if ["${JAVA_VERSION}" == "8"]; then
        choco install openjdk8
      else
        choco install openjdk11
      fi
    fi
    echo "JAVA_HOME=${JAVA_HOME}"
    which java && java -version

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2

branches:
    except:
        - gh-pages

notifications:
    email:
        - lennart.jorelid@gmail.com
